name: Build Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    env:
      python_ver: 3.10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .\requirements.txt --platform win_amd64 --target .\lib\ --only-binary=:all:
          Compress-Archive -Path (Get-ChildItem -Path . -Exclude ".git") -DestinationPath Flow.Launcher.Plugin.Ollama.zip
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: 'Flow.Launcher.Plugin.Ollama.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
